In [1]:
import numpy as np

In [2]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [3]:
a = -456
print(np.uint8(a))

56


C:\Users\SVasilchenko\AppData\Local\Temp\ipykernel_17460\3791078734.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -456 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  print(np.uint8(a))


In [9]:
x, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
step

0.45

In [15]:
roots = np.sqrt([4, 9 , -4 , 1])
roots

C:\Users\SVasilchenko\AppData\Local\Temp\ipykernel_9204\1018169628.py:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt([4, 9 , -4 , 1])


array([ 2.,  3., nan,  1.])

In [16]:
np.isnan(roots)

array([False, False,  True, False])

In [17]:
roots[np.isnan(roots)] = 0
roots

array([2., 3., 0., 1.])

In [27]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
                   [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
                   [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
                   [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
                   [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
                   [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
                   dtype=np.int16)

In [29]:
elem_5_3 = mystery[5, 3]
last = mystery[-1, -1]
line_4 = mystery[4, :]
col_2 = mystery[:, 1]
part = mystery[2:5, 3:6]
rev = mystery[::-1, -1]
trans = np.transpose(mystery)

In [45]:
mystery[:, ::-1]

array([[-18049, -17182,  -1781, -27117,  28445,  15203, -13586],
       [  7181,  15790,   6451,  -4593,  -1297, -30968,  25936],
       [  8225,  25397,  21762,  -6012,  28655,  28049,  13348],
       [  -564,  11795,  13754,  20149,  32592,   7994,  13240],
       [ 29943,  12578, -17918,  22260,  30305,  -8681, -21725],
       [-32037,    -47,   5916,  11740, -17278, -25392, -16841]],
      dtype=int16)

In [ ]:
order='F'

In [47]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

Получите булевый массив nans_index с информацией о np.nan в массиве mystery: True - значение пропущено, False - значение не пропущено

В переменную n_nan сохраните число пропущенных значений

Скопируйте массив mystery в массив mystery_new. Заполните пропущенные значения в массиве mystery_new нулями

Поменяйте тип данных в массиве mystery на int32 и сохраните в переменную mystery_int

Отсортируйте значения в массиве по возрастанию и сохраните результат в переменную array

Сохраните в массив table двухмерный массив, полученный из массива array. В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть по столбцам!

Сохраните в переменную col средний столбец из table

In [2]:
import numpy as np
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
nans_index = np.isnan(mystery)
n_nan = mystery[np.isnan(mystery)].size
mystery_new = np.copy(mystery)
mystery_new[np.isnan(mystery_new)] = 0
mystery_int = np.array(mystery, dtype=np.int32)
array = np.sort(mystery)
table = array.reshape((5, 3), order='F')
col = table[:, 1]

False
mystery =  [ 12279. -26024.  28745.     nan  31244.  -2365.  -6974.  -9212.     nan
 -17722.  16132.  25933.     nan -16431.  29810.]
mystery =  [ 12279. -26024.  28745.     nan  31244.  -2365.  -6974.  -9212.     nan
 -17722.  16132.  25933.     nan -16431.  29810.]
[-26024. -17722. -16431.  -9212.  -6974.  -2365.  12279.  16132.  25933.
  28745.  29810.  31244.     nan     nan     nan]
[[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]
[-2365. 12279. 16132. 25933. 28745.]


C:\Users\SVasilchenko\AppData\Local\Temp\ipykernel_14000\1324247394.py:12: RuntimeWarning: invalid value encountered in cast
  mystery_int = np.array(mystery, dtype=np.int32)


In [ ]:
import numpy as np

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

# Получите булевый массив с информацией о np.nan в массиве mystery
# True - значение пропущено, False - значение не пропущено
nans_index = np.isnan(mystery)

# В переменную n_nan сохраните число пропущенных значений
n_nan = sum(nans_index)

# Скопируйте массив `mystery` в массив `mystery_new`. Заполните пропущенные 
# значения в массиве `mystery_new` нулями
mystery_new = mystery.copy()
mystery_new[nans_index] = 0

# Поменяйте тип данных в массиве mystery на int32
mystery_int = np.int32(mystery)

# Отсортируйте значения в массиве по возрастанию и сохраните
# результат в переменную array
array = np.sort(mystery)

# Сохраните в массив table двухмерный массив, полученный из массива array
# В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть
# по столбцам! Например, 1, 2, 3, 4 -> 1    3
#                                      2    4
table = array.reshape((5,3), order='F')

#  Сохраните в переменную col столбец 2
col = table[:, 1]


In [7]:
a = np.array([23, 34, 27])
b = np.array([-54, 1, 46])
c = np.array([46, 68, 54])
length = np.linalg.norm(a)
distance = np.linalg.norm(b - c)
scalar_product = np.dot(a, b)
print(distance)


120.6358155772986


In [10]:
np.random.rand(2, 3, 4,3)

array([[[[0.99306838, 0.046181  , 0.70341952],
         [0.1621645 , 0.91649333, 0.4826697 ],
         [0.79523237, 0.98613031, 0.64598824],
         [0.24870718, 0.15060574, 0.26077689]],

        [[0.19672549, 0.21399948, 0.94545195],
         [0.495243  , 0.71802444, 0.3075183 ],
         [0.89576566, 0.55467428, 0.5632932 ],
         [0.41316962, 0.61428643, 0.07374647]],

        [[0.11391301, 0.71171631, 0.30042295],
         [0.11289862, 0.76699374, 0.53948259],
         [0.77013868, 0.43904628, 0.87365316],
         [0.06114967, 0.91851701, 0.81795607]]],


       [[[0.60159553, 0.78639015, 0.79618837],
         [0.57963337, 0.20235306, 0.31963842],
         [0.1984953 , 0.59772171, 0.01783828],
         [0.42356484, 0.60261173, 0.13922321]],

        [[0.99557113, 0.58099297, 0.83850362],
         [0.06872081, 0.02752334, 0.86850006],
         [0.55511781, 0.05751141, 0.97227777],
         [0.13613262, 0.06973436, 0.68656635]],

        [[0.11436208, 0.35544088, 0.5124991 ],
 

In [11]:
import numpy as np
np.random.rand()
# 0.06600758835806675

0.6411051311674281

In [ ]:
np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])
np.random.rand(2, 3)
# array([[0.94931212, 0.06680018, 0.26707599],
#      [0.67908873, 0.18001743, 0.97732239]])

In [12]:
shape = (3, 4)
np.random.rand(shape)
# TypeError: 'tuple' object cannot be interpreted as an integer
# Ошибка типов: кортеж не может быть интерпретирован как целое число.

TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
shape = (3, 4)
np.random.rand(*shape)
# array([[0.66169176, 0.19455777, 0.06451088, 0.31919608],
#        [0.73536951, 0.67104408, 0.4762727 , 0.88153576],
#        [0.70672971, 0.96677145, 0.09273995, 0.86356465]])

In [ ]:
shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

In [ ]:
'''uniform(low=0.0, high=1.0, size=None)'''

np.random.uniform(-30, 50)
# 38.47365525953661
np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])

In [ ]:
'''randint(low, high=None, size=None, dtype=int)'''

np.random.randint(4, size=(2,3))
# array([[3, 0, 1],
#       [2, 1, 3]])

In [ ]:
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

In [ ]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']b

In [16]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [18]:
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]
[2 2 2]


In [ ]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)
# [3 5 5 6 6 4 2 2 1 3]

В simple сохраните случайное число в диапазоне от 0 до 1

Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их в переменную randoms

Получите массив из случайных целых чисел от 1 до 100 (включительно) из 3 строк и 2 столбцов. Сохраните результат в table

В переменную even сохраните четные числа от 2 до 16 (включительно)

Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив изменился

Получите из even 3 числа без повторений. Сохраните их в переменную select

Получите переменную triplet, которая должна содержать перемешанные значения из массива select (сам select измениться не должен)

In [89]:
np.random.seed(2021)
simple = np.random.rand()
print(simple)
randoms = np.random.uniform(-150, 2021, size=120)
table = np.random.randint(1, 101, size=(3,2))
even = np.arange(2, 17, 2)
mix = even.copy()
print(mix)
np.random.shuffle(mix)
print(mix)
select = np.random.choice(even, 3, replace=False)
print(select)
triplet = np.random.permutation(select)
print(triplet)

0.6059782788074047
[ 2  4  6  8 10 12 14 16]
[ 6 10  2  8 14 16  4 12]
[14  2  4]
[ 2  4 14]


In [80]:
def get_chess(a):
    board = np.zeros((a,a))  
    board[1::2,::2] = 1
    board[::2,1::2] = 1
    return board

In [81]:
get_chess(1)

array([[0.]])

In [95]:
def shuffle_seed(arr):
    seed = np.random.randint(0, 2**32, dtype=np.uint32)
    np.random.seed(seed)
    shuffled = np.random.permutation(arr)
    return (shuffled, seed)

In [100]:
simple = np.random.randint(0, 11, 10)
shuffle_seed(simple)

(array([6, 9, 0, 7, 9, 0, 5, 4, 3, 3]), 4012171202)

In [114]:
from itertools import combinations
def min_max_dist(*vectors):
    comb = combinations(vectors, 2)
    dist = []
    for pair in comb:
       print(comb)
       vec1, vec2 = pair
       print(vec1, vec2)
       dist.append(np.linalg.norm(vec1 - vec2))
    d_min = min(dist)
    d_max = max(dist)
    return (d_min, d_max) 

In [115]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
min_max_dist(vec1, vec2, vec3)

[1 2 3] [4 5 6]
[1 2 3] [7 8 9]
[4 5 6] [7 8 9]


(5.196152422706632, 10.392304845413264)